server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://postgres-auth:5432/auth_db
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}