server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:auth_test_db
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: create-drop
  sql:
    init:
      mode: always