server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

jwt:
  secret: ${JWT_SECRET:jwt_secret_dev}
  expiration: ${JWT_EXPIRATION:3600000}

swagger:
  server:
    url: ${SWAGGER_SERVER_URL:http://localhost:8083}

springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /v3/api-docs